#!/usr/bin/env bash
# docs-index.sh — generate docs/INDEX.md: every heading of every docs/*.md with its line range and first sentence,
# so a brief can cite "ENGINEERING.md §2.2 (L68–94)" and an agent reads only that range (docs/TEAM.md).
#
#   scripts/docs-index.sh            # rewrite docs/INDEX.md
#   scripts/docs-index.sh --check    # exit 1 when the committed docs/INDEX.md is stale (run by ./validate.sh lint)
#
# A section's range runs from its heading to the line before the next heading of the same or a higher level.
# Headings inside fenced code blocks (``` or ~~~, at any indent) are ignored. The generator's output is already
# prettier-clean (presetup.sh and sync-from-template.sh run it without node_modules); when prettier is installed the
# output is passed through it as well so any future formatting rule still holds, and --check compares against that.
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
docs_dir="$repo_root/docs"
index_file="$docs_dir/INDEX.md"

index_one_document() {
  local path="$1"
  awk '
    function flush(i) {
      if (count == 0) return
      for (i = 1; i <= count; i++) {
        end = NR
        for (j = i + 1; j <= count; j++) if (level[j] <= level[i]) { end = line[j] - 1; break }
        printf "%s- **%s** (L%d–%d)%s\n", indent[i], title[i], line[i], end, (summary[i] == "" ? "" : ": " summary[i])
      }
    }
    /^[[:space:]]*(```|~~~)/ { fenced = !fenced; next }
    fenced { next }
    /^#{1,6} / {
      count++
      match($0, /^#+/)
      level[count] = RLENGTH
      indent[count] = (level[count] <= 2 ? "" : "  ")
      title[count] = substr($0, RLENGTH + 2)
      line[count] = NR
      summary[count] = ""
      want = count
      buffer = ""
      next
    }
    want && $0 ~ /^[[:space:]]*$/ { if (buffer != "") finish(); else next }
    want && $0 !~ /^[|>]/ && $0 !~ /^<!--/ && $0 !~ /^[[:space:]]*([-*]|[0-9]+\.) / {
      s = $0
      gsub(/^[[:space:]]+|[[:space:]]+$/, "", s)
      buffer = (buffer == "" ? s : buffer " " s)
      if (match(buffer, /[.!?]( |$)/)) finish()
      next
    }
    want && buffer != "" { finish() }
    function finish() {
      s = buffer
      gsub(/\*\*/, "", s)
      if (match(s, /[.!?]( |$)/)) s = substr(s, 1, RSTART)
      summary[want] = s
      want = 0
      buffer = ""
    }
    END { flush() }
  ' "$path"
}

generate() {
  echo "# docs/ index"
  echo
  echo "Generated by \`scripts/docs-index.sh\` — do not edit by hand. Cite sections as \`FILE.md §heading (Lstart–end)\`"
  echo "and read only that line range (\`sed -n 'start,endp' docs/FILE.md\`). Regenerate after editing any doc; \`./validate.sh lint\` checks it."
  local path name
  for path in "$docs_dir"/*.md; do
    name="$(basename "$path")"
    [[ "$name" == "INDEX.md" ]] && continue
    echo
    echo "## $name ($(wc -l < "$path") lines)"
    echo
    index_one_document "$path"
  done
}

have_prettier() { [[ -x "$repo_root/node_modules/.bin/prettier" ]]; }

format() {
  if have_prettier; then
    (cd "$repo_root" && node_modules/.bin/prettier --stdin-filepath docs/INDEX.md)
  else
    cat
  fi
}

if [[ "${1:-}" == "--check" ]]; then
  if ! have_prettier; then
    echo "docs/INDEX.md freshness not checked: prettier is not installed here (run pnpm install)" >&2
    exit 0
  fi
  if [[ -f "$index_file" ]] && diff -u "$index_file" <(generate | format) >/dev/null 2>&1; then
    echo "docs/INDEX.md is up to date"
  else
    echo "docs/INDEX.md is stale: run scripts/docs-index.sh and commit the result" >&2
    exit 1
  fi
else
  generated="$(generate | format)"
  printf '%s\n' "$generated" > "$index_file"
  echo "wrote $index_file ($(grep -c '^ *- ' "$index_file") sections)"
fi
